# Site settings
title: Professor of Internet Studies
name: Fabio Giglietto
email: fabio.giglietto@uniurb.it
description: >-
  Academic profile and portfolio for Fabio Giglietto, featuring research, 
  publications, projects, and teaching information.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://fabiogiglietto.github.io" # the base hostname & protocol

# Content settings
citation_style: "APA 7" # Publication citation style

# Profile settings
profile_image: /assets/images/profile.jpg
position: Professor
affiliation: University of Urbino
location: Department of Communication Sciences, Humanities and International Studies
use_generated_about: true

# Verification (set via environment variable for security)
# google_site_verification: # Set GOOGLE_SITE_VERIFICATION in your environment

# Social links
github_username: fabiogiglietto
orcid_id: 0000-0001-8019-1035
scholar_id: FmenbcUAAAAJ
threads_username: fabiogiglietto
linkedin_username: fabiogiglietto
mastodon_instance: aoir.social
mastodon_username: fabiogiglietto
bluesky_username: fabiogiglietto.bsky.social

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude from processing
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/
  - scripts/
  - README.md
  - package.json
  - package-lock.json
  - LICENSE
  - CLAUDE.md
